language: python
python:
  - "3.6.3"
node_js:
  - node
cache:
  directories:
    - node_modules
    - $HOME/virtualenv/python3.6.3/lib/python3.6/site-packages
    - $HOME/.cache/pip
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - npm install -g serverless
  - npm install
script:
  - sls deploy
